spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 155
    driverClassName: org.postgresql.Driver
  config:
    import: optional:application.localUserInfo.yaml
server:
  port: 9090